### ISSUE TITLE
No field mCursorDrawableRes in class Landroid/widget/TextView

### ISSUE THREAD

**Issue by furqanyasin** [mancj/MaterialSearchBar#141]
`W/System.err:` java.lang.NoSuchFieldException: No field mCursorDrawableRes in class Landroid/widget/TextView; (declaration of 'android.widget.TextView' appears in /system/framework/framework.jar!classes3.dex)
        at java.lang.Class.getDeclaredField(Native Method)
        at com.mancj.materialsearchbar.MaterialSearchBar.setupCursorColor(MaterialSearchBar.java:317)
        at com.mancj.materialsearchbar.MaterialSearchBar.setupSearchEditText(MaterialSearchBar.java:300)
        at com.mancj.materialsearchbar.MaterialSearchBar.postSetup(MaterialSearchBar.java:265)
        at com.mancj.materialsearchbar.MaterialSearchBar.init(MaterialSearchBar.java:207)
        at com.mancj.materialsearchbar.MaterialSearchBar.<init>(MaterialSearchBar.java:117)
W/System.err:     at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:854)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
        at com.beingknow.eatit2020.Activities.FoodListActivity.onCreate(FoodListActivity.java:54)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by bchandresh** [comment]
Same problem with me. Did you find any solution?

**Comment by furqanyasin** [comment]
> Same problem with me. Did you find any solution?

No solution founded

**Comment by YorkPeng** [comment]
I also have the same problem.

**Comment by gurk0001** [comment]
Any solution for this?

**Comment by furqanyasin** [comment]
I'm playing with libraries version after some how it works. but originally we need solution for it

**Comment by AlaJaber97** [comment]
Any solution for this?

**Comment by Rita-Hygge** [comment]
How did you fix it?

**Comment by pallaviwaghaye** [comment]
I am also facing same issue, any solution is there for this ?
