### ISSUE TITLE
EditTextStyleChangeError

### ISSUE THREAD

**Issue by r3dm4n** [mancj/MaterialSearchBar#84]
W/nitoruldegalat: Accessing hidden field Landroid/widget/TextView;->mCursorDrawableRes:I (light greylist, reflection)
09-10 16:39:55.294 16710-16710/io.spaceapps.monitoruldegalati E/ContentValues: init: 
    com.mancj.materialsearchbar.EditTextStyleHelper$EditTextStyleChangeError: Error applying changes to android.support.v7.widget.AppCompatEditText{a7d5bfc VFED..CL. ......I. 0,0-0,0 #7f080080 app:id/mt_editText}
        at com.mancj.materialsearchbar.EditTextStyleHelper.apply(EditTextStyleHelper.java:125)
        at com.mancj.materialsearchbar.EditTextStyleHelper.applyChanges(EditTextStyleHelper.java:40)
        at com.mancj.materialsearchbar.MaterialSearchBar.setupSearchEditText(MaterialSearchBar.java:317)
        at com.mancj.materialsearchbar.MaterialSearchBar.postSetup(MaterialSearchBar.java:281)
        at com.mancj.materialsearchbar.MaterialSearchBar.init(MaterialSearchBar.java:223)
        at com.mancj.materialsearchbar.MaterialSearchBar.<init>(MaterialSearchBar.java:126)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)

**Comment by lucasvieirawerner** [comment]
having the same error

**Comment by p32929** [comment]
I'm also facing the same error if I run the app on Android Pie Emulator

**Comment by TheGamingGuy** [comment]
Same issue here, testing on Pie

**Comment by tomventom** [comment]
Same issue on Pie. Is this gonna be fixed?
