### ISSUE TITLE
Unknown animation name: objectAnimator

### ISSUE THREAD

**Issue by T3RON** [mancj/MaterialSearchBar#96]
**Unknown animation name: objectAnimator**
        at android.view.animation.AnimationUtils.createAnimationFromXml(AnimationUtils.java:128)
        at android.view.animation.AnimationUtils.createAnimationFromXml(AnimationUtils.java:118)
        at android.view.animation.AnimationUtils.createAnimationFromXml(AnimationUtils.java:118)
        at android.view.animation.AnimationUtils.createAnimationFromXml(AnimationUtils.java:95)
        at android.view.animation.AnimationUtils.loadAnimation(AnimationUtils.java:76)
        at com.mancj.materialsearchbar.MaterialSearchBar.enableSearch(MaterialSearchBar.java:467)
        at com.mancj.materialsearchbar.MaterialSearchBar.onClick(MaterialSearchBar.java:906)
        at android.view.View.performClick(View.java:5610)
        at android.view.View$PerformClick.run(View.java:22265)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)

**Comment by dreamsparkx** [comment]
I got the same error.

**Comment by mome13** [comment]
Looks like you are trying to use objectAnimator in the support fragments library, but it was added in Android API level 11.
